#!/bin/bash

#TODO
# Get all the local IP/hostname in a multi-server environment!!

mydir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" || { echo "Couldn't determine the script's running directory, which probably matters, bailing out" >&2; exit 2; }
. "$mydir/utilfunc.sh"  # '.' means 'source'
. "$mydir/argparser.sh"

u=`id -un`
if [ x$u != "xroot" ]; then
    echo "Error: must be run as root user"
    exit 1
fi

# Get Ubuntu Version
version=$(lsb_release -d | awk -F" " '{print $3}' | cut -c 1-5)
if [[ x$version == "x20.04" || x$version == "x18.04" ]]; then
   echo "Ubuntu $version is supported."
else
   echo "Ubuntu $version is not supported!"
   exit 1
fi

configVariables
#updateSystemPackages
#installDNS
#fixFirewall
#pingLicenseServer
#resetHostName
#resetTimeDate
#configCert
#miscConfig
downloadBinaries
createConfig
#getLicense
#postInstallCert
#postInstallZimbra

su - zimbra -c '/opt/zimbra/bin/zmcontrol restart'

echo
echo
echo "Zimbra installation details:"
echo
echo "  - Webmail Login:  https://${HOSTNAME}"
echo "  - Admin Console:  https://${HOSTNAME}:9071"
echo "  - Admin Username: admin"
echo "  - Admin Password: ${MYPASSWORD}"
echo ""